#!/usr/bin/env perl
use strict;
use warnings;
use Harriet;
use Pod::Usage;

my $dir = shift or pod2usage;

my $harriet = Harriet->new($dir);
my %vars = $harriet->load_all();
print "\n\n";
print $harriet->variables_as_string(%vars) . "\n";

# and long long sleep.
sleep 10000 while 1;

__END__

=head1 NAME

harriet - daemons runner for testing

=head1 SYNOPSIS

    % harriet t/harriet/

=head1 DESCRIPTION

Run the harriet scripts in t/harriet/.
